language: python
sudo: false
dist: xenial
os: linux

matrix:
  fast_finish: false
  include:
    - env: ENV=lint
      python: 3.7
      before_install: TOX_ENV=lint
    - env: ENV=py2.7-unit-tests
      python: 2.7
      before_install: TOX_ENV=py2.7-unit-tests
    - env: ENV=py3.6-unit-tests
      python: 3.6
      before_install: TOX_ENV=py3.6-unit-tests
    - env: ENV=py3.7-unit-tests
      python: 3.7
      before_install: TOX_ENV=py3.7-unit-tests
    - env: ENV=integration-tests
      python: 3.7
      before_install: TOX_ENV=py3.7-integration-tests
    - env: ENV=coverage
      python: 3.7
      before_install: TOX_ENV=coverage-travis

install:
  - pip install "tox==3.12.1"
  - if [ ${TOX_ENV} = "py3.7-integration-tests" ] || [ ${TOX_ENV} = "coverage-travis" ]; then ./scripts/run-datastore-emulator.sh; fi

script:
  - tox -e $TOX_ENV

cache:
  apt: true
  directories:
    - $HOME/.cache/pip # pip cache
    - .benchmarks/  # py.test-benchmark result cache
#    - .tox
