language: python
sudo: false
dist: xenial
os: linux

matrix:
  fast_finish: false
  include:
    - env: ENV=lint
      python: 3.7
      before_install: TOX_ENV=lint
    - env: ENV=py2.7-unit-tests
      python: 2.7
      before_install: TOX_ENV=py2.7-unit-tests
    - env: ENV=py3.6-unit-tests
      python: 3.6
      before_install: TOX_ENV=py3.6-unit-tests
    - env: ENV=py3.7-unit-tests
      python: 3.7
      before_install: TOX_ENV=py3.7-unit-tests
    - env: ENV=py2.7-integration-tests
      python: 2.7
      before_install: TOX_ENV=py2.7-integration-tests
    - env: ENV=py3.7-integration-tests
      python: 3.7
      before_install: TOX_ENV=py3.7-integration-tests
    - env: ENV=coverage
      python: 3.7
      before_install: TOX_ENV=coverage-travis
    - env: ENV=py2.7-benchmarks
      python: 2.7
      before_install: TOX_ENV=py2.7-benchmarks-travis
    - env: ENV=py3.6-benchmarks
      python: 3.6
      before_install: TOX_ENV=py3.6-benchmarks-travis
    - env: ENV=py3.7-benchmarks
      python: 3.7
      before_install: TOX_ENV=py3.7-benchmarks-travis

install:
  - pip install "tox==3.12.1"
  # Install Go
  - if [ ${TOX_ENV} = "py2.7-integration-tests" ] || [ ${TOX_ENV} = "py3.7-integration-tests" ] || [ ${TOX_ENV} = "coverage-travis" ]; then eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=1.12 bash)"; fi
  # NOTE: This binary is required for cross programming language compatibility tests
  - if [ ${TOX_ENV} = "py2.7-integration-tests" ] || [ ${TOX_ENV} = "py3.7-integration-tests" ] || [ ${TOX_ENV} = "coverage-travis" ]; then ./scripts/build-go-binary.sh; fi
  - if [ ${TOX_ENV} = "py2.7-integration-tests" ] || [ ${TOX_ENV} = "py3.7-integration-tests" ] || [ ${TOX_ENV} = "coverage-travis" ]; then ./scripts/run-datastore-emulator.sh; fi

script:
  - tox -e $TOX_ENV

cache:
  apt: true
  directories:
    - $HOME/.cache/pip # pip cache
    - .benchmarks/  # py.test-benchmark result cache
#    - .tox
